version: "3"
services:


  server:
    build: server/
    image: server
    container_name: server_year_end_project
    ports:
      - "8080:8080"
    networks:
      - year-end-project
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.7.1-focal
    container_name: services
    ports:
      - "3306:3306"
    networks:
      - year-end-project
    command: --init-file /docker-entrypoint-initdb.d/dump.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/services/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - services:/var/lib/mysql
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: year-end-project
      MARIADB_ROOT_PASSWORD: rootpassword
    restart: always

networks:
  year-end-project:
    driver: bridge

volumes:
  mariadb:
