version: "3"
services:
  client_web:
    build: web/
    image: web
    container_name : client_web_area
    ports:
      - "8081:8081"
    networks:
      - area
    volumes:
      - apk:/app/public/:ro
    depends_on:
      - client_mobile
      - server
    restart: always

  client_mobile:
    build: mobile/
    image: mobile
    container_name : client_mobile_area
    volumes:
      - apk:/app/android/app/build/outputs/apk/:rw

  server:
    build: server/
    image: server
    container_name: server_area
    ports:
      - "8082:8082"
    networks:
      - area
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - area
    volumes:
      - ./server/nginx/conf:/etc/nginx/conf.d:ro
      - ./server/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - server
    restart: always

  mariadb:
    image: mariadb:10.7.1-focal
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - area
    command: --init-file /docker-entrypoint-initdb.d/dump.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mariadb/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: area
      MARIADB_ROOT_PASSWORD: rootpassword
    restart: always

networks:
  area:
    driver: bridge

volumes:
  mariadb:
  apk: