version: "3"
services:
  client_web:
    build: web/
    image: web
    container_name : client_web_yep
    ports:
      - "8081:8081"
    networks:
      - yep
    restart: always

  server:
    build: server/
    image: server
    container_name: server_yep
    ports:
      - "8080:8080"
    networks:
      - yep
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.7.1-focal
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - yep
    command: --init-file /docker-entrypoint-initdb.d/dump.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mariadb/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: yep
      MARIADB_ROOT_PASSWORD: rootpassword
    restart: always

networks:
  yep:
    driver: bridge

volumes:
  mariadb: