name: "Build Server"
on:
  push:
    branches:
      - master
      - dev/*
      - devops
      - server
      - client
      - mobile
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    container: node:16-alpine3.13
    steps:
      - uses: actions/checkout@v2
      - name: Install all dependencies
        run: npm i
        working-directory: server
      - name: Create production build for server
        run: npm run build
        working-directory: server